-- Review names and grants before production use.
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS AMN_DEV COMMENT = 'AMN development data platform';
CREATE SCHEMA IF NOT EXISTS AMN_DEV.RAW COMMENT = 'Append-only source-aligned data';
CREATE SCHEMA IF NOT EXISTS AMN_DEV.CURATED COMMENT = 'Validated business entities';
CREATE SCHEMA IF NOT EXISTS AMN_DEV.MARTS COMMENT = 'Power BI serving models';
CREATE SCHEMA IF NOT EXISTS AMN_DEV.CONTROL COMMENT = 'Pipeline control plane';
CREATE SCHEMA IF NOT EXISTS AMN_DEV.QUARANTINE COMMENT = 'Rejected records';

CREATE WAREHOUSE IF NOT EXISTS AMN_INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE COMMENT = 'Ingestion workload';
CREATE WAREHOUSE IF NOT EXISTS AMN_TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE COMMENT = 'Transformation workload';
CREATE WAREHOUSE IF NOT EXISTS AMN_BI_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE COMMENT = 'Analytics workload';

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS AMN_INGEST_ROLE;
CREATE ROLE IF NOT EXISTS AMN_TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS AMN_BI_ROLE;

GRANT USAGE ON DATABASE AMN_DEV TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.RAW TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.CONTROL TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE AMN_INGEST_WH TO ROLE AMN_INGEST_ROLE;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA AMN_DEV.RAW TO ROLE AMN_INGEST_ROLE;
GRANT CREATE TABLE ON SCHEMA AMN_DEV.CONTROL TO ROLE AMN_INGEST_ROLE;

GRANT USAGE ON DATABASE AMN_DEV TO ROLE AMN_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.RAW TO ROLE AMN_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.CURATED TO ROLE AMN_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.CONTROL TO ROLE AMN_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE AMN_TRANSFORM_WH TO ROLE AMN_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AMN_DEV.RAW TO ROLE AMN_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AMN_DEV.RAW TO ROLE AMN_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TASK, CREATE DYNAMIC TABLE ON SCHEMA AMN_DEV.CURATED TO ROLE AMN_TRANSFORM_ROLE;

GRANT USAGE ON DATABASE AMN_DEV TO ROLE AMN_BI_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.MARTS TO ROLE AMN_BI_ROLE;
GRANT USAGE ON WAREHOUSE AMN_BI_WH TO ROLE AMN_BI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AMN_DEV.MARTS TO ROLE AMN_BI_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AMN_DEV.MARTS TO ROLE AMN_BI_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA AMN_DEV.MARTS TO ROLE AMN_BI_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AMN_DEV.MARTS TO ROLE AMN_BI_ROLE;

GRANT ROLE AMN_INGEST_ROLE TO ROLE SYSADMIN;
GRANT ROLE AMN_TRANSFORM_ROLE TO ROLE SYSADMIN;
GRANT ROLE AMN_BI_ROLE TO ROLE SYSADMIN;

