USE ROLE SYSADMIN;
USE WAREHOUSE AMN_TRANSFORM_WH;
USE DATABASE AMN_DEV;
USE SCHEMA CONTROL;

CREATE TABLE IF NOT EXISTS INGESTION_CONFIG (
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SOURCE_OBJECT VARCHAR NOT NULL,
  SOURCE_PATH VARCHAR NOT NULL,
  TARGET_SCHEMA VARCHAR NOT NULL DEFAULT 'RAW',
  TARGET_TABLE VARCHAR NOT NULL,
  LOAD_TYPE VARCHAR NOT NULL,
  PRIMARY_KEY_COLUMNS VARCHAR NOT NULL,
  WATERMARK_COLUMN VARCHAR,
  SLA_SECONDS NUMBER(10, 0) NOT NULL,
  ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_INGESTION_CONFIG PRIMARY KEY (SOURCE_SYSTEM, SOURCE_OBJECT),
  CONSTRAINT CK_LOAD_TYPE CHECK (LOAD_TYPE IN ('CDC', 'WATERMARK', 'SNAPSHOT'))
);

CREATE TABLE IF NOT EXISTS PIPELINE_RUN_LOG (
  RUN_ID VARCHAR NOT NULL,
  BATCH_ID VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SOURCE_OBJECT VARCHAR NOT NULL,
  TARGET_TABLE VARCHAR NOT NULL,
  SOURCE_HIGH_WATERMARK TIMESTAMP_NTZ,
  EXTRACT_STARTED_AT TIMESTAMP_NTZ,
  EXTRACT_FINISHED_AT TIMESTAMP_NTZ,
  RAW_LOADED_AT TIMESTAMP_NTZ,
  CURATED_AT TIMESTAMP_NTZ,
  ROWS_READ NUMBER(38, 0) DEFAULT 0,
  ROWS_INSERTED NUMBER(38, 0) DEFAULT 0,
  ROWS_UPDATED NUMBER(38, 0) DEFAULT 0,
  ROWS_DELETED NUMBER(38, 0) DEFAULT 0,
  ROWS_REJECTED NUMBER(38, 0) DEFAULT 0,
  STATUS VARCHAR NOT NULL,
  RETRY_COUNT NUMBER(10, 0) DEFAULT 0,
  ERROR_CATEGORY VARCHAR,
  ERROR_MESSAGE VARCHAR,
  CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_PIPELINE_RUN_LOG PRIMARY KEY (RUN_ID, SOURCE_OBJECT),
  CONSTRAINT CK_RUN_STATUS CHECK (STATUS IN ('STARTED', 'SUCCEEDED', 'FAILED', 'QUARANTINED'))
);

CREATE TABLE IF NOT EXISTS LOAD_CHECKPOINT (
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SOURCE_OBJECT VARCHAR NOT NULL,
  TARGET_TABLE VARCHAR NOT NULL,
  LAST_WATERMARK TIMESTAMP_NTZ,
  LAST_BATCH_ID VARCHAR,
  UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_LOAD_CHECKPOINT PRIMARY KEY (SOURCE_SYSTEM, SOURCE_OBJECT)
);

CREATE TABLE IF NOT EXISTS DATA_QUALITY_RESULT (
  RUN_ID VARCHAR NOT NULL,
  SOURCE_OBJECT VARCHAR NOT NULL,
  CHECK_NAME VARCHAR NOT NULL,
  CHECK_TYPE VARCHAR NOT NULL,
  OBSERVED_VALUE VARCHAR,
  EXPECTED_VALUE VARCHAR,
  PASSED BOOLEAN NOT NULL,
  IS_BLOCKING BOOLEAN NOT NULL DEFAULT TRUE,
  DETAILS VARCHAR,
  CHECKED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW PIPELINE_FRESHNESS AS
SELECT
  R.SOURCE_SYSTEM,
  R.SOURCE_OBJECT,
  R.RUN_ID,
  R.STATUS,
  C.SLA_SECONDS,
  R.SOURCE_HIGH_WATERMARK,
  R.CURATED_AT,
  DATEDIFF('second', R.SOURCE_HIGH_WATERMARK, R.CURATED_AT) AS FRESHNESS_SECONDS,
  IFF(R.STATUS = 'SUCCEEDED'
      AND R.SOURCE_HIGH_WATERMARK IS NOT NULL
      AND R.CURATED_AT IS NOT NULL
      AND DATEDIFF('second', R.SOURCE_HIGH_WATERMARK, R.CURATED_AT) <= C.SLA_SECONDS,
      TRUE, FALSE) AS WITHIN_SLA
FROM PIPELINE_RUN_LOG AS R
LEFT JOIN INGESTION_CONFIG AS C
  ON R.SOURCE_SYSTEM = C.SOURCE_SYSTEM
 AND R.SOURCE_OBJECT = C.SOURCE_OBJECT;

