-- Step 23-25: idempotent hospitals transformation.
-- Run the object creation as SYSADMIN. The owner-rights procedure lets ADF's
-- AMN_INGEST_ROLE execute the merge without broad write access to CURATED.

USE ROLE SYSADMIN;
USE WAREHOUSE AMN_TRANSFORM_WH;
USE DATABASE AMN_DEV;
USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS HOSPITALS (
  HOSPITAL_ID VARCHAR NOT NULL,
  HOSPITAL_NAME VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  HOSPITAL_TYPE VARCHAR,
  OWNERSHIP VARCHAR,
  EMERGENCY_SERVICES BOOLEAN,
  HOSPITAL_RATING NUMBER(2, 0),
  CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_HOSPITALS PRIMARY KEY (HOSPITAL_ID)
);

CREATE OR REPLACE PROCEDURE MERGE_HOSPITALS()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  AFFECTED_ROWS NUMBER DEFAULT 0;
  CURATED_ROWS NUMBER DEFAULT 0;
BEGIN
  MERGE INTO AMN_DEV.CURATED.HOSPITALS AS T
  USING (
    SELECT
      NULLIF(TRIM(HOSPITAL_ID), '') AS HOSPITAL_ID,
      NULLIF(TRIM(HOSPITAL_NAME), '') AS HOSPITAL_NAME,
      NULLIF(TRIM(CITY), '') AS CITY,
      NULLIF(TRIM(STATE), '') AS STATE,
      NULLIF(TRIM(HOSPITAL_TYPE), '') AS HOSPITAL_TYPE,
      NULLIF(TRIM(OWNERSHIP), '') AS OWNERSHIP,
      CASE
        WHEN UPPER(TRIM(EMERGENCY_SERVICES)) IN ('YES', 'TRUE', 'Y', '1') THEN TRUE
        WHEN UPPER(TRIM(EMERGENCY_SERVICES)) IN ('NO', 'FALSE', 'N', '0') THEN FALSE
        ELSE NULL
      END AS EMERGENCY_SERVICES,
      TRY_TO_NUMBER(NULLIF(TRIM(HOSPITAL_RATING), '')) AS HOSPITAL_RATING
    FROM AMN_DEV.RAW.HOSPITALS
    WHERE NULLIF(TRIM(HOSPITAL_ID), '') IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY NULLIF(TRIM(HOSPITAL_ID), '')
      ORDER BY _INGESTED_AT DESC NULLS LAST
    ) = 1
  ) AS S
    ON T.HOSPITAL_ID = S.HOSPITAL_ID
  WHEN MATCHED AND (
       T.HOSPITAL_NAME IS DISTINCT FROM S.HOSPITAL_NAME
    OR T.CITY IS DISTINCT FROM S.CITY
    OR T.STATE IS DISTINCT FROM S.STATE
    OR T.HOSPITAL_TYPE IS DISTINCT FROM S.HOSPITAL_TYPE
    OR T.OWNERSHIP IS DISTINCT FROM S.OWNERSHIP
    OR T.EMERGENCY_SERVICES IS DISTINCT FROM S.EMERGENCY_SERVICES
    OR T.HOSPITAL_RATING IS DISTINCT FROM S.HOSPITAL_RATING
  ) THEN UPDATE SET
    HOSPITAL_NAME = S.HOSPITAL_NAME,
    CITY = S.CITY,
    STATE = S.STATE,
    HOSPITAL_TYPE = S.HOSPITAL_TYPE,
    OWNERSHIP = S.OWNERSHIP,
    EMERGENCY_SERVICES = S.EMERGENCY_SERVICES,
    HOSPITAL_RATING = S.HOSPITAL_RATING,
    UPDATED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    HOSPITAL_TYPE,
    OWNERSHIP,
    EMERGENCY_SERVICES,
    HOSPITAL_RATING
  ) VALUES (
    S.HOSPITAL_ID,
    S.HOSPITAL_NAME,
    S.CITY,
    S.STATE,
    S.HOSPITAL_TYPE,
    S.OWNERSHIP,
    S.EMERGENCY_SERVICES,
    S.HOSPITAL_RATING
  );

  AFFECTED_ROWS := SQLROWCOUNT;
  SELECT COUNT(*) INTO :CURATED_ROWS
  FROM AMN_DEV.CURATED.HOSPITALS;

  RETURN OBJECT_CONSTRUCT(
    'status', 'SUCCEEDED',
    'affected_rows', AFFECTED_ROWS,
    'curated_row_count', CURATED_ROWS,
    'completed_at', CURRENT_TIMESTAMP()
  );
END;
$$;

USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE AMN_DEV TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.CURATED TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CURATED.MERGE_HOSPITALS()
  TO ROLE AMN_INGEST_ROLE;

-- Manual test. Run twice; the second call should report zero affected rows.
USE ROLE AMN_INGEST_ROLE;
USE WAREHOUSE AMN_INGEST_WH;
CALL AMN_DEV.CURATED.MERGE_HOSPITALS();

SELECT COUNT(*) AS CURATED_ROWS
FROM AMN_DEV.CURATED.HOSPITALS;

SELECT HOSPITAL_ID, COUNT(*) AS ROW_COUNT
FROM AMN_DEV.CURATED.HOSPITALS
GROUP BY HOSPITAL_ID
HAVING COUNT(*) > 1;
