-- Step 26: owner-rights audit procedures for the hospitals ADF pipeline.

USE ROLE SYSADMIN;
USE WAREHOUSE AMN_TRANSFORM_WH;
USE DATABASE AMN_DEV;
USE SCHEMA CONTROL;

CREATE OR REPLACE PROCEDURE START_HOSPITALS_RUN(
  P_RUN_ID VARCHAR,
  P_BATCH_ID VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  MERGE INTO AMN_DEV.CONTROL.PIPELINE_RUN_LOG AS T
  USING (
    SELECT
      :P_RUN_ID AS RUN_ID,
      :P_BATCH_ID AS BATCH_ID
  ) AS S
    ON T.RUN_ID = S.RUN_ID
   AND T.SOURCE_OBJECT = 'HOSPITALS'
  WHEN MATCHED THEN UPDATE SET
    BATCH_ID = S.BATCH_ID,
    STATUS = 'STARTED',
    EXTRACT_STARTED_AT = CURRENT_TIMESTAMP(),
    EXTRACT_FINISHED_AT = NULL,
    RAW_LOADED_AT = NULL,
    CURATED_AT = NULL,
    ROWS_READ = 0,
    ROWS_INSERTED = 0,
    ROWS_UPDATED = 0,
    ROWS_DELETED = 0,
    ROWS_REJECTED = 0,
    ERROR_CATEGORY = NULL,
    ERROR_MESSAGE = NULL
  WHEN NOT MATCHED THEN INSERT (
    RUN_ID,
    BATCH_ID,
    SOURCE_SYSTEM,
    SOURCE_OBJECT,
    TARGET_TABLE,
    EXTRACT_STARTED_AT,
    STATUS
  ) VALUES (
    S.RUN_ID,
    S.BATCH_ID,
    'CMS',
    'HOSPITALS',
    'AMN_DEV.CURATED.HOSPITALS',
    CURRENT_TIMESTAMP(),
    'STARTED'
  );

  RETURN 'STARTED';
END;
$$;

CREATE OR REPLACE PROCEDURE SUCCEED_HOSPITALS_RUN(
  P_RUN_ID VARCHAR,
  P_ROWS_READ NUMBER,
  P_ROWS_COPIED NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  UPDATE AMN_DEV.CONTROL.PIPELINE_RUN_LOG
  SET
    EXTRACT_FINISHED_AT = CURRENT_TIMESTAMP(),
    RAW_LOADED_AT = CURRENT_TIMESTAMP(),
    CURATED_AT = CURRENT_TIMESTAMP(),
    ROWS_READ = COALESCE(:P_ROWS_READ, 0),
    ROWS_INSERTED = COALESCE(:P_ROWS_COPIED, 0),
    STATUS = 'SUCCEEDED',
    ERROR_CATEGORY = NULL,
    ERROR_MESSAGE = NULL
  WHERE RUN_ID = :P_RUN_ID
    AND SOURCE_OBJECT = 'HOSPITALS';

  RETURN 'SUCCEEDED';
END;
$$;

CREATE OR REPLACE PROCEDURE FAIL_HOSPITALS_RUN(
  P_RUN_ID VARCHAR,
  P_ERROR_CATEGORY VARCHAR,
  P_ERROR_MESSAGE VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  UPDATE AMN_DEV.CONTROL.PIPELINE_RUN_LOG
  SET
    EXTRACT_FINISHED_AT = CURRENT_TIMESTAMP(),
    STATUS = 'FAILED',
    ERROR_CATEGORY = LEFT(:P_ERROR_CATEGORY, 500),
    ERROR_MESSAGE = LEFT(:P_ERROR_MESSAGE, 8000)
  WHERE RUN_ID = :P_RUN_ID
    AND SOURCE_OBJECT = 'HOSPITALS';

  RETURN 'FAILED';
END;
$$;

USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE AMN_DEV TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.CONTROL TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CONTROL.START_HOSPITALS_RUN(VARCHAR, VARCHAR)
  TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CONTROL.SUCCEED_HOSPITALS_RUN(VARCHAR, NUMBER, NUMBER)
  TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CONTROL.FAIL_HOSPITALS_RUN(VARCHAR, VARCHAR, VARCHAR)
  TO ROLE AMN_INGEST_ROLE;
