-- Required once when RAW tables were created by SYSADMIN rather than AMN_INGEST_ROLE.
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE AMN_DEV TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.RAW TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE AMN_INGEST_WH TO ROLE AMN_INGEST_ROLE;
GRANT CREATE STAGE ON SCHEMA AMN_DEV.RAW TO ROLE AMN_INGEST_ROLE;

GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA AMN_DEV.RAW
  TO ROLE AMN_INGEST_ROLE;

GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA AMN_DEV.RAW
  TO ROLE AMN_INGEST_ROLE;

SHOW GRANTS TO ROLE AMN_INGEST_ROLE;
