-- Corrects the four HR RAW tables that were created with non-source schemas.
-- DESTRUCTIVE FOR THESE FOUR TABLES: CREATE OR REPLACE removes any existing rows.
-- Safe for the current setup only because their ADF Copy runs have not succeeded.
USE ROLE SYSADMIN;
USE WAREHOUSE AMN_INGEST_WH;
USE DATABASE AMN_DEV;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CANDIDATES (
  CANDIDATE_ID VARCHAR,
  REQUEST_ID VARCHAR,
  HOSPITAL_ID VARCHAR,
  HOSPITAL_NAME VARCHAR,
  RECRUITER_ID VARCHAR,
  CANDIDATE_NAME VARCHAR,
  EMAIL VARCHAR,
  PHONE VARCHAR,
  PROFESSION VARCHAR,
  DEPARTMENT VARCHAR,
  EXPERIENCE_YEARS VARCHAR,
  LICENSE_STATE VARCHAR,
  LICENSE_STATUS VARCHAR,
  CERTIFICATIONS VARCHAR,
  SOURCE_CHANNEL VARCHAR,
  APPLICATION_DATE VARCHAR,
  CANDIDATE_STATUS VARCHAR,
  BACKGROUND_CHECK_STATUS VARCHAR,
  CREDENTIAL_STATUS VARCHAR,
  EMPLOYEE_ID VARCHAR,
  _BATCH_ID VARCHAR,
  _SOURCE_FILE VARCHAR,
  _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STAFFING_REQUESTS (
  REQUEST_ID VARCHAR,
  HOSPITAL_ID VARCHAR,
  HOSPITAL_NAME VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  REQUIRED_ROLE VARCHAR,
  DEPARTMENT VARCHAR,
  EMPLOYMENT_TYPE VARCHAR,
  SHIFT_PREFERENCE VARCHAR,
  REQUIRED_STAFF VARCHAR,
  FILLED_STAFF VARCHAR,
  OPEN_POSITIONS VARCHAR,
  PRIORITY VARCHAR,
  REQUEST_STATUS VARCHAR,
  REQUEST_DATE VARCHAR,
  ASSIGNMENT_START_DATE VARCHAR,
  ASSIGNMENT_END_DATE VARCHAR,
  DURATION_WEEKS VARCHAR,
  HOURLY_BILL_RATE VARCHAR,
  _BATCH_ID VARCHAR,
  _SOURCE_FILE VARCHAR,
  _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SCHEDULES (
  SCHEDULE_ID VARCHAR,
  EMPLOYEE_ID VARCHAR,
  REQUEST_ID VARCHAR,
  HOSPITAL_ID VARCHAR,
  HOSPITAL_NAME VARCHAR,
  WORK_DATE VARCHAR,
  SHIFT_TYPE VARCHAR,
  SHIFT_START_TIME VARCHAR,
  SHIFT_END_TIME VARCHAR,
  PLANNED_HOURS VARCHAR,
  WORKED_HOURS VARCHAR,
  OVERTIME_HOURS VARCHAR,
  SCHEDULE_STATUS VARCHAR,
  _BATCH_ID VARCHAR,
  _SOURCE_FILE VARCHAR,
  _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PAYROLL (
  PAYROLL_ID VARCHAR,
  EMPLOYEE_ID VARCHAR,
  HOSPITAL_ID VARCHAR,
  HOSPITAL_NAME VARCHAR,
  PAYROLL_MONTH VARCHAR,
  REGULAR_HOURS VARCHAR,
  OVERTIME_HOURS VARCHAR,
  HOURLY_PAY_RATE VARCHAR,
  REGULAR_PAY VARCHAR,
  OVERTIME_PAY VARCHAR,
  BONUS VARCHAR,
  GROSS_PAY VARCHAR,
  TAX_AMOUNT VARCHAR,
  BENEFITS_DEDUCTION VARCHAR,
  NET_PAY VARCHAR,
  PAYMENT_STATUS VARCHAR,
  _BATCH_ID VARCHAR,
  _SOURCE_FILE VARCHAR,
  _INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

USE ROLE SECURITYADMIN;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA AMN_DEV.RAW TO ROLE AMN_INGEST_ROLE;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA AMN_DEV.RAW TO ROLE AMN_INGEST_ROLE;

USE ROLE AMN_INGEST_ROLE;
USE WAREHOUSE AMN_INGEST_WH;
SELECT 'CANDIDATES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM AMN_DEV.RAW.CANDIDATES
UNION ALL SELECT 'STAFFING_REQUESTS', COUNT(*) FROM AMN_DEV.RAW.STAFFING_REQUESTS
UNION ALL SELECT 'SCHEDULES', COUNT(*) FROM AMN_DEV.RAW.SCHEDULES
UNION ALL SELECT 'PAYROLL', COUNT(*) FROM AMN_DEV.RAW.PAYROLL;

