-- Step 27: typed CURATED tables, idempotent merges, and generic HR audit APIs.
USE ROLE SYSADMIN;
USE WAREHOUSE AMN_TRANSFORM_WH;
USE DATABASE AMN_DEV;

CREATE TABLE IF NOT EXISTS CURATED.STAFFING_REQUESTS (
  REQUEST_ID VARCHAR NOT NULL, HOSPITAL_ID VARCHAR, HOSPITAL_NAME VARCHAR,
  CITY VARCHAR, STATE VARCHAR, REQUIRED_ROLE VARCHAR, DEPARTMENT VARCHAR,
  EMPLOYMENT_TYPE VARCHAR, SHIFT_PREFERENCE VARCHAR,
  REQUIRED_STAFF NUMBER(10,0), FILLED_STAFF NUMBER(10,0), OPEN_POSITIONS NUMBER(10,0),
  PRIORITY VARCHAR, REQUEST_STATUS VARCHAR, REQUEST_DATE DATE,
  ASSIGNMENT_START_DATE DATE, ASSIGNMENT_END_DATE DATE, DURATION_WEEKS NUMBER(10,0),
  HOURLY_BILL_RATE NUMBER(12,2), CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_STAFFING_REQUESTS PRIMARY KEY (REQUEST_ID)
);

CREATE TABLE IF NOT EXISTS CURATED.CANDIDATES (
  CANDIDATE_ID VARCHAR NOT NULL, REQUEST_ID VARCHAR, HOSPITAL_ID VARCHAR,
  HOSPITAL_NAME VARCHAR, RECRUITER_ID VARCHAR, CANDIDATE_NAME VARCHAR,
  EMAIL VARCHAR, PHONE VARCHAR, PROFESSION VARCHAR, DEPARTMENT VARCHAR,
  EXPERIENCE_YEARS NUMBER(10,0), LICENSE_STATE VARCHAR, LICENSE_STATUS VARCHAR,
  CERTIFICATIONS VARCHAR, SOURCE_CHANNEL VARCHAR, APPLICATION_DATE DATE,
  CANDIDATE_STATUS VARCHAR, BACKGROUND_CHECK_STATUS VARCHAR,
  CREDENTIAL_STATUS VARCHAR, EMPLOYEE_ID VARCHAR,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_CANDIDATES PRIMARY KEY (CANDIDATE_ID)
);

CREATE TABLE IF NOT EXISTS CURATED.SCHEDULES (
  SCHEDULE_ID VARCHAR NOT NULL, EMPLOYEE_ID VARCHAR, REQUEST_ID VARCHAR,
  HOSPITAL_ID VARCHAR, HOSPITAL_NAME VARCHAR, WORK_DATE DATE, SHIFT_TYPE VARCHAR,
  SHIFT_START_TIME TIME, SHIFT_END_TIME TIME, PLANNED_HOURS NUMBER(10,2),
  WORKED_HOURS NUMBER(10,2), OVERTIME_HOURS NUMBER(10,2), SCHEDULE_STATUS VARCHAR,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_SCHEDULES PRIMARY KEY (SCHEDULE_ID)
);

CREATE TABLE IF NOT EXISTS CURATED.PAYROLL (
  PAYROLL_ID VARCHAR NOT NULL, EMPLOYEE_ID VARCHAR, HOSPITAL_ID VARCHAR,
  HOSPITAL_NAME VARCHAR, PAYROLL_MONTH VARCHAR, REGULAR_HOURS NUMBER(10,2),
  OVERTIME_HOURS NUMBER(10,2), HOURLY_PAY_RATE NUMBER(12,2), REGULAR_PAY NUMBER(14,2),
  OVERTIME_PAY NUMBER(14,2), BONUS NUMBER(14,2), GROSS_PAY NUMBER(14,2),
  TAX_AMOUNT NUMBER(14,2), BENEFITS_DEDUCTION NUMBER(14,2), NET_PAY NUMBER(14,2),
  PAYMENT_STATUS VARCHAR, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_PAYROLL PRIMARY KEY (PAYROLL_ID)
);

CREATE OR REPLACE PROCEDURE CURATED.MERGE_STAFFING_REQUESTS()
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS OWNER AS $$
BEGIN
  MERGE INTO CURATED.STAFFING_REQUESTS T USING (
    SELECT REQUEST_ID,HOSPITAL_ID,HOSPITAL_NAME,CITY,STATE,REQUIRED_ROLE,DEPARTMENT,
      EMPLOYMENT_TYPE,SHIFT_PREFERENCE,TRY_TO_NUMBER(REQUIRED_STAFF) REQUIRED_STAFF,
      TRY_TO_NUMBER(FILLED_STAFF) FILLED_STAFF,TRY_TO_NUMBER(OPEN_POSITIONS) OPEN_POSITIONS,
      PRIORITY,REQUEST_STATUS,TRY_TO_DATE(REQUEST_DATE) REQUEST_DATE,
      TRY_TO_DATE(ASSIGNMENT_START_DATE) ASSIGNMENT_START_DATE,
      TRY_TO_DATE(ASSIGNMENT_END_DATE) ASSIGNMENT_END_DATE,
      TRY_TO_NUMBER(DURATION_WEEKS) DURATION_WEEKS,TRY_TO_DECIMAL(HOURLY_BILL_RATE,12,2) HOURLY_BILL_RATE
    FROM RAW.STAFFING_REQUESTS WHERE NULLIF(TRIM(REQUEST_ID),'') IS NOT NULL
    QUALIFY ROW_NUMBER() OVER(PARTITION BY REQUEST_ID ORDER BY _INGESTED_AT DESC NULLS LAST)=1
  ) S ON T.REQUEST_ID=S.REQUEST_ID
  WHEN MATCHED THEN UPDATE SET HOSPITAL_ID=S.HOSPITAL_ID,HOSPITAL_NAME=S.HOSPITAL_NAME,CITY=S.CITY,
    STATE=S.STATE,REQUIRED_ROLE=S.REQUIRED_ROLE,DEPARTMENT=S.DEPARTMENT,EMPLOYMENT_TYPE=S.EMPLOYMENT_TYPE,
    SHIFT_PREFERENCE=S.SHIFT_PREFERENCE,REQUIRED_STAFF=S.REQUIRED_STAFF,FILLED_STAFF=S.FILLED_STAFF,
    OPEN_POSITIONS=S.OPEN_POSITIONS,PRIORITY=S.PRIORITY,REQUEST_STATUS=S.REQUEST_STATUS,
    REQUEST_DATE=S.REQUEST_DATE,ASSIGNMENT_START_DATE=S.ASSIGNMENT_START_DATE,
    ASSIGNMENT_END_DATE=S.ASSIGNMENT_END_DATE,DURATION_WEEKS=S.DURATION_WEEKS,
    HOURLY_BILL_RATE=S.HOURLY_BILL_RATE,UPDATED_AT=CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (REQUEST_ID,HOSPITAL_ID,HOSPITAL_NAME,CITY,STATE,REQUIRED_ROLE,DEPARTMENT,
    EMPLOYMENT_TYPE,SHIFT_PREFERENCE,REQUIRED_STAFF,FILLED_STAFF,OPEN_POSITIONS,PRIORITY,REQUEST_STATUS,
    REQUEST_DATE,ASSIGNMENT_START_DATE,ASSIGNMENT_END_DATE,DURATION_WEEKS,HOURLY_BILL_RATE)
  VALUES(S.REQUEST_ID,S.HOSPITAL_ID,S.HOSPITAL_NAME,S.CITY,S.STATE,S.REQUIRED_ROLE,S.DEPARTMENT,
    S.EMPLOYMENT_TYPE,S.SHIFT_PREFERENCE,S.REQUIRED_STAFF,S.FILLED_STAFF,S.OPEN_POSITIONS,S.PRIORITY,
    S.REQUEST_STATUS,S.REQUEST_DATE,S.ASSIGNMENT_START_DATE,S.ASSIGNMENT_END_DATE,S.DURATION_WEEKS,S.HOURLY_BILL_RATE);
  RETURN 'SUCCEEDED';
END; $$;

CREATE OR REPLACE PROCEDURE CURATED.MERGE_CANDIDATES()
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS OWNER AS $$
BEGIN
  MERGE INTO CURATED.CANDIDATES T USING (
    SELECT CANDIDATE_ID,REQUEST_ID,HOSPITAL_ID,HOSPITAL_NAME,RECRUITER_ID,CANDIDATE_NAME,EMAIL,PHONE,
      PROFESSION,DEPARTMENT,TRY_TO_NUMBER(EXPERIENCE_YEARS) EXPERIENCE_YEARS,LICENSE_STATE,LICENSE_STATUS,
      CERTIFICATIONS,SOURCE_CHANNEL,TRY_TO_DATE(APPLICATION_DATE) APPLICATION_DATE,CANDIDATE_STATUS,
      BACKGROUND_CHECK_STATUS,CREDENTIAL_STATUS,EMPLOYEE_ID
    FROM RAW.CANDIDATES WHERE NULLIF(TRIM(CANDIDATE_ID),'') IS NOT NULL
    QUALIFY ROW_NUMBER() OVER(PARTITION BY CANDIDATE_ID ORDER BY _INGESTED_AT DESC NULLS LAST)=1
  ) S ON T.CANDIDATE_ID=S.CANDIDATE_ID
  WHEN MATCHED THEN UPDATE SET REQUEST_ID=S.REQUEST_ID,HOSPITAL_ID=S.HOSPITAL_ID,HOSPITAL_NAME=S.HOSPITAL_NAME,
    RECRUITER_ID=S.RECRUITER_ID,CANDIDATE_NAME=S.CANDIDATE_NAME,EMAIL=S.EMAIL,PHONE=S.PHONE,
    PROFESSION=S.PROFESSION,DEPARTMENT=S.DEPARTMENT,EXPERIENCE_YEARS=S.EXPERIENCE_YEARS,
    LICENSE_STATE=S.LICENSE_STATE,LICENSE_STATUS=S.LICENSE_STATUS,CERTIFICATIONS=S.CERTIFICATIONS,
    SOURCE_CHANNEL=S.SOURCE_CHANNEL,APPLICATION_DATE=S.APPLICATION_DATE,CANDIDATE_STATUS=S.CANDIDATE_STATUS,
    BACKGROUND_CHECK_STATUS=S.BACKGROUND_CHECK_STATUS,CREDENTIAL_STATUS=S.CREDENTIAL_STATUS,
    EMPLOYEE_ID=S.EMPLOYEE_ID,UPDATED_AT=CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (CANDIDATE_ID,REQUEST_ID,HOSPITAL_ID,HOSPITAL_NAME,RECRUITER_ID,CANDIDATE_NAME,
    EMAIL,PHONE,PROFESSION,DEPARTMENT,EXPERIENCE_YEARS,LICENSE_STATE,LICENSE_STATUS,CERTIFICATIONS,
    SOURCE_CHANNEL,APPLICATION_DATE,CANDIDATE_STATUS,BACKGROUND_CHECK_STATUS,CREDENTIAL_STATUS,EMPLOYEE_ID)
  VALUES(S.CANDIDATE_ID,S.REQUEST_ID,S.HOSPITAL_ID,S.HOSPITAL_NAME,S.RECRUITER_ID,S.CANDIDATE_NAME,S.EMAIL,
    S.PHONE,S.PROFESSION,S.DEPARTMENT,S.EXPERIENCE_YEARS,S.LICENSE_STATE,S.LICENSE_STATUS,S.CERTIFICATIONS,
    S.SOURCE_CHANNEL,S.APPLICATION_DATE,S.CANDIDATE_STATUS,S.BACKGROUND_CHECK_STATUS,S.CREDENTIAL_STATUS,S.EMPLOYEE_ID);
  RETURN 'SUCCEEDED';
END; $$;

CREATE OR REPLACE PROCEDURE CURATED.MERGE_SCHEDULES()
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS OWNER AS $$
BEGIN
  MERGE INTO CURATED.SCHEDULES T USING (
    SELECT SCHEDULE_ID,EMPLOYEE_ID,REQUEST_ID,HOSPITAL_ID,HOSPITAL_NAME,TRY_TO_DATE(WORK_DATE) WORK_DATE,
      SHIFT_TYPE,TRY_TO_TIME(SHIFT_START_TIME) SHIFT_START_TIME,TRY_TO_TIME(SHIFT_END_TIME) SHIFT_END_TIME,
      TRY_TO_DECIMAL(PLANNED_HOURS,10,2) PLANNED_HOURS,TRY_TO_DECIMAL(WORKED_HOURS,10,2) WORKED_HOURS,
      TRY_TO_DECIMAL(OVERTIME_HOURS,10,2) OVERTIME_HOURS,SCHEDULE_STATUS
    FROM RAW.SCHEDULES WHERE NULLIF(TRIM(SCHEDULE_ID),'') IS NOT NULL
    QUALIFY ROW_NUMBER() OVER(PARTITION BY SCHEDULE_ID ORDER BY _INGESTED_AT DESC NULLS LAST)=1
  ) S ON T.SCHEDULE_ID=S.SCHEDULE_ID
  WHEN MATCHED THEN UPDATE SET EMPLOYEE_ID=S.EMPLOYEE_ID,REQUEST_ID=S.REQUEST_ID,HOSPITAL_ID=S.HOSPITAL_ID,
    HOSPITAL_NAME=S.HOSPITAL_NAME,WORK_DATE=S.WORK_DATE,SHIFT_TYPE=S.SHIFT_TYPE,
    SHIFT_START_TIME=S.SHIFT_START_TIME,SHIFT_END_TIME=S.SHIFT_END_TIME,PLANNED_HOURS=S.PLANNED_HOURS,
    WORKED_HOURS=S.WORKED_HOURS,OVERTIME_HOURS=S.OVERTIME_HOURS,SCHEDULE_STATUS=S.SCHEDULE_STATUS,
    UPDATED_AT=CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (SCHEDULE_ID,EMPLOYEE_ID,REQUEST_ID,HOSPITAL_ID,HOSPITAL_NAME,WORK_DATE,
    SHIFT_TYPE,SHIFT_START_TIME,SHIFT_END_TIME,PLANNED_HOURS,WORKED_HOURS,OVERTIME_HOURS,SCHEDULE_STATUS)
  VALUES(S.SCHEDULE_ID,S.EMPLOYEE_ID,S.REQUEST_ID,S.HOSPITAL_ID,S.HOSPITAL_NAME,S.WORK_DATE,S.SHIFT_TYPE,
    S.SHIFT_START_TIME,S.SHIFT_END_TIME,S.PLANNED_HOURS,S.WORKED_HOURS,S.OVERTIME_HOURS,S.SCHEDULE_STATUS);
  RETURN 'SUCCEEDED';
END; $$;

CREATE OR REPLACE PROCEDURE CURATED.MERGE_PAYROLL()
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS OWNER AS $$
BEGIN
  MERGE INTO CURATED.PAYROLL T USING (
    SELECT PAYROLL_ID,EMPLOYEE_ID,HOSPITAL_ID,HOSPITAL_NAME,PAYROLL_MONTH,
      TRY_TO_DECIMAL(REGULAR_HOURS,10,2) REGULAR_HOURS,TRY_TO_DECIMAL(OVERTIME_HOURS,10,2) OVERTIME_HOURS,
      TRY_TO_DECIMAL(HOURLY_PAY_RATE,12,2) HOURLY_PAY_RATE,TRY_TO_DECIMAL(REGULAR_PAY,14,2) REGULAR_PAY,
      TRY_TO_DECIMAL(OVERTIME_PAY,14,2) OVERTIME_PAY,TRY_TO_DECIMAL(BONUS,14,2) BONUS,
      TRY_TO_DECIMAL(GROSS_PAY,14,2) GROSS_PAY,TRY_TO_DECIMAL(TAX_AMOUNT,14,2) TAX_AMOUNT,
      TRY_TO_DECIMAL(BENEFITS_DEDUCTION,14,2) BENEFITS_DEDUCTION,TRY_TO_DECIMAL(NET_PAY,14,2) NET_PAY,
      PAYMENT_STATUS FROM RAW.PAYROLL WHERE NULLIF(TRIM(PAYROLL_ID),'') IS NOT NULL
    QUALIFY ROW_NUMBER() OVER(PARTITION BY PAYROLL_ID ORDER BY _INGESTED_AT DESC NULLS LAST)=1
  ) S ON T.PAYROLL_ID=S.PAYROLL_ID
  WHEN MATCHED THEN UPDATE SET EMPLOYEE_ID=S.EMPLOYEE_ID,HOSPITAL_ID=S.HOSPITAL_ID,HOSPITAL_NAME=S.HOSPITAL_NAME,
    PAYROLL_MONTH=S.PAYROLL_MONTH,REGULAR_HOURS=S.REGULAR_HOURS,OVERTIME_HOURS=S.OVERTIME_HOURS,
    HOURLY_PAY_RATE=S.HOURLY_PAY_RATE,REGULAR_PAY=S.REGULAR_PAY,OVERTIME_PAY=S.OVERTIME_PAY,BONUS=S.BONUS,
    GROSS_PAY=S.GROSS_PAY,TAX_AMOUNT=S.TAX_AMOUNT,BENEFITS_DEDUCTION=S.BENEFITS_DEDUCTION,
    NET_PAY=S.NET_PAY,PAYMENT_STATUS=S.PAYMENT_STATUS,UPDATED_AT=CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (PAYROLL_ID,EMPLOYEE_ID,HOSPITAL_ID,HOSPITAL_NAME,PAYROLL_MONTH,REGULAR_HOURS,
    OVERTIME_HOURS,HOURLY_PAY_RATE,REGULAR_PAY,OVERTIME_PAY,BONUS,GROSS_PAY,TAX_AMOUNT,BENEFITS_DEDUCTION,
    NET_PAY,PAYMENT_STATUS) VALUES(S.PAYROLL_ID,S.EMPLOYEE_ID,S.HOSPITAL_ID,S.HOSPITAL_NAME,S.PAYROLL_MONTH,
    S.REGULAR_HOURS,S.OVERTIME_HOURS,S.HOURLY_PAY_RATE,S.REGULAR_PAY,S.OVERTIME_PAY,S.BONUS,S.GROSS_PAY,
    S.TAX_AMOUNT,S.BENEFITS_DEDUCTION,S.NET_PAY,S.PAYMENT_STATUS);
  RETURN 'SUCCEEDED';
END; $$;

CREATE OR REPLACE PROCEDURE CONTROL.START_HR_RUN(P_RUN_ID VARCHAR,P_BATCH_ID VARCHAR,P_OBJECT VARCHAR)
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS OWNER AS $$
BEGIN
  INSERT INTO CONTROL.PIPELINE_RUN_LOG(RUN_ID,BATCH_ID,SOURCE_SYSTEM,SOURCE_OBJECT,TARGET_TABLE,EXTRACT_STARTED_AT,STATUS)
  VALUES(:P_RUN_ID,:P_BATCH_ID,'HR',:P_OBJECT,'AMN_DEV.CURATED.'||:P_OBJECT,CURRENT_TIMESTAMP(),'STARTED');
  RETURN 'STARTED';
END; $$;

CREATE OR REPLACE PROCEDURE CONTROL.SUCCEED_HR_RUN(P_RUN_ID VARCHAR,P_OBJECT VARCHAR,P_ROWS_READ NUMBER,P_ROWS_COPIED NUMBER)
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS OWNER AS $$
BEGIN
  UPDATE CONTROL.PIPELINE_RUN_LOG SET EXTRACT_FINISHED_AT=CURRENT_TIMESTAMP(),RAW_LOADED_AT=CURRENT_TIMESTAMP(),
    CURATED_AT=CURRENT_TIMESTAMP(),ROWS_READ=:P_ROWS_READ,ROWS_INSERTED=:P_ROWS_COPIED,STATUS='SUCCEEDED'
  WHERE RUN_ID=:P_RUN_ID AND SOURCE_OBJECT=:P_OBJECT;
  RETURN 'SUCCEEDED';
END; $$;

CREATE OR REPLACE PROCEDURE CONTROL.FAIL_HR_RUN(P_RUN_ID VARCHAR,P_OBJECT VARCHAR,P_CATEGORY VARCHAR,P_MESSAGE VARCHAR)
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS OWNER AS $$
BEGIN
  UPDATE CONTROL.PIPELINE_RUN_LOG SET EXTRACT_FINISHED_AT=CURRENT_TIMESTAMP(),STATUS='FAILED',
    ERROR_CATEGORY=LEFT(:P_CATEGORY,500),ERROR_MESSAGE=LEFT(:P_MESSAGE,8000)
  WHERE RUN_ID=:P_RUN_ID AND SOURCE_OBJECT=:P_OBJECT;
  RETURN 'FAILED';
END; $$;

USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA AMN_DEV.CURATED TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.CONTROL TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CURATED.MERGE_STAFFING_REQUESTS() TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CURATED.MERGE_CANDIDATES() TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CURATED.MERGE_SCHEDULES() TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CURATED.MERGE_PAYROLL() TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CONTROL.START_HR_RUN(VARCHAR,VARCHAR,VARCHAR) TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CONTROL.SUCCEED_HR_RUN(VARCHAR,VARCHAR,NUMBER,NUMBER) TO ROLE AMN_INGEST_ROLE;
GRANT USAGE ON PROCEDURE AMN_DEV.CONTROL.FAIL_HR_RUN(VARCHAR,VARCHAR,VARCHAR,VARCHAR) TO ROLE AMN_INGEST_ROLE;

USE ROLE AMN_INGEST_ROLE;
USE WAREHOUSE AMN_INGEST_WH;
CALL AMN_DEV.CURATED.MERGE_STAFFING_REQUESTS();
CALL AMN_DEV.CURATED.MERGE_CANDIDATES();
CALL AMN_DEV.CURATED.MERGE_SCHEDULES();
CALL AMN_DEV.CURATED.MERGE_PAYROLL();
