-- Step 28: seed metadata used by PL_METADATA_INGEST and grant ADF read access.
USE ROLE SYSADMIN;
USE WAREHOUSE AMN_TRANSFORM_WH;
USE DATABASE AMN_DEV;

MERGE INTO CONTROL.INGESTION_CONFIG AS T
USING (
  SELECT * FROM VALUES
    ('CMS','HOSPITALS','landing/cms/hospitals/hospitals_reference.csv','RAW','HOSPITALS','SNAPSHOT','HOSPITAL_ID',NULL,86400,TRUE),
    ('HR','STAFFING_REQUESTS','landing/hr/staffing_requests/staffing_requests.csv','RAW','STAFFING_REQUESTS','SNAPSHOT','REQUEST_ID',NULL,180,TRUE),
    ('HR','CANDIDATES','landing/hr/candidates/candidates.csv','RAW','CANDIDATES','SNAPSHOT','CANDIDATE_ID',NULL,900,TRUE),
    ('HR','SCHEDULES','landing/hr/schedules/schedules.csv','RAW','SCHEDULES','SNAPSHOT','SCHEDULE_ID',NULL,180,TRUE),
    ('HR','PAYROLL','landing/hr/payroll/payroll.csv','RAW','PAYROLL','SNAPSHOT','PAYROLL_ID',NULL,86400,TRUE)
  AS V(SOURCE_SYSTEM,SOURCE_OBJECT,SOURCE_PATH,TARGET_SCHEMA,TARGET_TABLE,LOAD_TYPE,PRIMARY_KEY_COLUMNS,WATERMARK_COLUMN,SLA_SECONDS,ENABLED)
) AS S
ON T.SOURCE_SYSTEM=S.SOURCE_SYSTEM AND T.SOURCE_OBJECT=S.SOURCE_OBJECT
WHEN MATCHED THEN UPDATE SET SOURCE_PATH=S.SOURCE_PATH,TARGET_SCHEMA=S.TARGET_SCHEMA,TARGET_TABLE=S.TARGET_TABLE,LOAD_TYPE=S.LOAD_TYPE,PRIMARY_KEY_COLUMNS=S.PRIMARY_KEY_COLUMNS,WATERMARK_COLUMN=S.WATERMARK_COLUMN,SLA_SECONDS=S.SLA_SECONDS,ENABLED=S.ENABLED,UPDATED_AT=CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (SOURCE_SYSTEM,SOURCE_OBJECT,SOURCE_PATH,TARGET_SCHEMA,TARGET_TABLE,LOAD_TYPE,PRIMARY_KEY_COLUMNS,WATERMARK_COLUMN,SLA_SECONDS,ENABLED)
VALUES (S.SOURCE_SYSTEM,S.SOURCE_OBJECT,S.SOURCE_PATH,S.TARGET_SCHEMA,S.TARGET_TABLE,S.LOAD_TYPE,S.PRIMARY_KEY_COLUMNS,S.WATERMARK_COLUMN,S.SLA_SECONDS,S.ENABLED);

USE ROLE SECURITYADMIN;
GRANT SELECT ON TABLE AMN_DEV.CONTROL.INGESTION_CONFIG TO ROLE AMN_INGEST_ROLE;