-- Power BI serving layer for the AMN staffing dashboard.
-- Run object creation as SYSADMIN, then grants as SECURITYADMIN.

USE ROLE SYSADMIN;
USE WAREHOUSE AMN_TRANSFORM_WH;
USE DATABASE AMN_DEV;
USE SCHEMA MARTS;

CREATE OR REPLACE VIEW DIM_HOSPITAL AS
SELECT
  HOSPITAL_ID,
  HOSPITAL_NAME,
  CITY,
  STATE,
  HOSPITAL_TYPE,
  OWNERSHIP,
  EMERGENCY_SERVICES,
  HOSPITAL_RATING
FROM AMN_DEV.CURATED.HOSPITALS;

-- PII such as email and phone is intentionally excluded from the BI layer.
CREATE OR REPLACE VIEW DIM_CANDIDATE AS
SELECT
  CANDIDATE_ID,
  REQUEST_ID,
  HOSPITAL_ID,
  RECRUITER_ID,
  PROFESSION,
  DEPARTMENT,
  EXPERIENCE_YEARS,
  LICENSE_STATE,
  LICENSE_STATUS,
  CERTIFICATIONS,
  SOURCE_CHANNEL,
  APPLICATION_DATE,
  CANDIDATE_STATUS,
  BACKGROUND_CHECK_STATUS,
  CREDENTIAL_STATUS,
  EMPLOYEE_ID
FROM AMN_DEV.CURATED.CANDIDATES;

CREATE OR REPLACE VIEW DIM_DATE AS
WITH DATES AS (
  SELECT REQUEST_DATE AS DATE_VALUE FROM AMN_DEV.CURATED.STAFFING_REQUESTS
  UNION
  SELECT ASSIGNMENT_START_DATE FROM AMN_DEV.CURATED.STAFFING_REQUESTS
  UNION
  SELECT ASSIGNMENT_END_DATE FROM AMN_DEV.CURATED.STAFFING_REQUESTS
  UNION
  SELECT APPLICATION_DATE FROM AMN_DEV.CURATED.CANDIDATES
  UNION
  SELECT WORK_DATE FROM AMN_DEV.CURATED.SCHEDULES
)
SELECT
  DATE_VALUE AS FULL_DATE,
  YEAR(DATE_VALUE) AS YEAR_NUMBER,
  QUARTER(DATE_VALUE) AS QUARTER_NUMBER,
  MONTH(DATE_VALUE) AS MONTH_NUMBER,
  MONTHNAME(DATE_VALUE) AS MONTH_NAME,
  WEEKOFYEAR(DATE_VALUE) AS WEEK_NUMBER,
  DAYOFMONTH(DATE_VALUE) AS DAY_OF_MONTH,
  DAYNAME(DATE_VALUE) AS DAY_NAME
FROM DATES
WHERE DATE_VALUE IS NOT NULL;

CREATE OR REPLACE VIEW FACT_STAFFING_REQUEST AS
WITH CANDIDATE_SUMMARY AS (
  SELECT
    REQUEST_ID,
    COUNT(*) AS CANDIDATE_COUNT,
    COUNT_IF(EMPLOYEE_ID IS NOT NULL) AS PLACED_CANDIDATE_COUNT,
    COUNT_IF(UPPER(CANDIDATE_STATUS) IN ('AVAILABLE', 'ACTIVE', 'QUALIFIED')) AS AVAILABLE_CANDIDATE_COUNT
  FROM AMN_DEV.CURATED.CANDIDATES
  GROUP BY REQUEST_ID
),
SCHEDULE_SUMMARY AS (
  SELECT
    REQUEST_ID,
    COUNT(*) AS SCHEDULE_COUNT,
    SUM(COALESCE(PLANNED_HOURS, 0)) AS PLANNED_HOURS,
    SUM(COALESCE(WORKED_HOURS, 0)) AS WORKED_HOURS,
    SUM(COALESCE(OVERTIME_HOURS, 0)) AS OVERTIME_HOURS
  FROM AMN_DEV.CURATED.SCHEDULES
  GROUP BY REQUEST_ID
)
SELECT
  R.REQUEST_ID,
  R.HOSPITAL_ID,
  R.HOSPITAL_NAME,
  R.CITY,
  R.STATE,
  R.REQUIRED_ROLE,
  R.DEPARTMENT,
  R.EMPLOYMENT_TYPE,
  R.SHIFT_PREFERENCE,
  R.REQUIRED_STAFF,
  R.FILLED_STAFF,
  R.OPEN_POSITIONS,
  R.PRIORITY,
  R.REQUEST_STATUS,
  R.REQUEST_DATE,
  R.ASSIGNMENT_START_DATE,
  R.ASSIGNMENT_END_DATE,
  R.DURATION_WEEKS,
  R.HOURLY_BILL_RATE,
  IFF(UPPER(R.REQUEST_STATUS) IN ('OPEN', 'PENDING', 'IN PROGRESS'), TRUE, FALSE) AS IS_OPEN_REQUEST,
  IFF(COALESCE(R.REQUIRED_STAFF, 0) = 0, NULL,
      R.FILLED_STAFF / R.REQUIRED_STAFF::NUMBER(18, 4)) AS FILL_RATE,
  IFF(COALESCE(R.FILLED_STAFF, 0) > 0 AND R.ASSIGNMENT_START_DATE IS NOT NULL,
      DATEDIFF('day', R.REQUEST_DATE, R.ASSIGNMENT_START_DATE), NULL) AS TIME_TO_FILL_DAYS,
  COALESCE(C.CANDIDATE_COUNT, 0) AS CANDIDATE_COUNT,
  COALESCE(C.PLACED_CANDIDATE_COUNT, 0) AS ACTIVE_PLACEMENT_COUNT,
  COALESCE(C.AVAILABLE_CANDIDATE_COUNT, 0) AS AVAILABLE_CANDIDATE_COUNT,
  COALESCE(S.SCHEDULE_COUNT, 0) AS SCHEDULE_COUNT,
  COALESCE(S.PLANNED_HOURS, 0) AS PLANNED_HOURS,
  COALESCE(S.WORKED_HOURS, 0) AS WORKED_HOURS,
  COALESCE(S.OVERTIME_HOURS, 0) AS OVERTIME_HOURS
FROM AMN_DEV.CURATED.STAFFING_REQUESTS R
LEFT JOIN CANDIDATE_SUMMARY C ON R.REQUEST_ID = C.REQUEST_ID
LEFT JOIN SCHEDULE_SUMMARY S ON R.REQUEST_ID = S.REQUEST_ID;

CREATE OR REPLACE VIEW FACT_PLACEMENT_SCHEDULE AS
SELECT
  S.SCHEDULE_ID,
  S.EMPLOYEE_ID,
  S.REQUEST_ID,
  S.HOSPITAL_ID,
  S.HOSPITAL_NAME,
  S.WORK_DATE,
  S.SHIFT_TYPE,
  S.SHIFT_START_TIME,
  S.SHIFT_END_TIME,
  S.PLANNED_HOURS,
  S.WORKED_HOURS,
  S.OVERTIME_HOURS,
  S.SCHEDULE_STATUS,
  R.REQUIRED_ROLE,
  R.DEPARTMENT,
  R.STATE,
  C.CANDIDATE_ID,
  C.RECRUITER_ID,
  C.PROFESSION
FROM AMN_DEV.CURATED.SCHEDULES S
LEFT JOIN AMN_DEV.CURATED.STAFFING_REQUESTS R ON S.REQUEST_ID = R.REQUEST_ID
LEFT JOIN AMN_DEV.CURATED.CANDIDATES C
  ON S.EMPLOYEE_ID = C.EMPLOYEE_ID
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY S.SCHEDULE_ID
  ORDER BY C.UPDATED_AT DESC NULLS LAST, C.CANDIDATE_ID
) = 1;

CREATE OR REPLACE VIEW FACT_PAYROLL AS
SELECT
  PAYROLL_ID,
  EMPLOYEE_ID,
  HOSPITAL_ID,
  HOSPITAL_NAME,
  PAYROLL_MONTH,
  TRY_TO_DATE(PAYROLL_MONTH || '-01') AS PAYROLL_MONTH_DATE,
  REGULAR_HOURS,
  OVERTIME_HOURS,
  HOURLY_PAY_RATE,
  REGULAR_PAY,
  OVERTIME_PAY,
  BONUS,
  GROSS_PAY,
  TAX_AMOUNT,
  BENEFITS_DEDUCTION,
  NET_PAY,
  PAYMENT_STATUS
FROM AMN_DEV.CURATED.PAYROLL;

CREATE OR REPLACE VIEW VW_RECRUITING_FUNNEL AS
SELECT
  APPLICATION_DATE,
  HOSPITAL_ID,
  RECRUITER_ID,
  PROFESSION,
  DEPARTMENT,
  LICENSE_STATE,
  SOURCE_CHANNEL,
  CANDIDATE_STATUS,
  BACKGROUND_CHECK_STATUS,
  CREDENTIAL_STATUS,
  COUNT(*) AS CANDIDATE_COUNT,
  COUNT_IF(EMPLOYEE_ID IS NOT NULL) AS PLACEMENT_COUNT
FROM AMN_DEV.CURATED.CANDIDATES
GROUP BY ALL;

CREATE OR REPLACE VIEW VW_EXECUTIVE_KPIS AS
SELECT
  COUNT(*) AS TOTAL_REQUESTS,
  COUNT_IF(IS_OPEN_REQUEST) AS OPEN_REQUESTS,
  SUM(COALESCE(REQUIRED_STAFF, 0)) AS REQUIRED_STAFF,
  SUM(COALESCE(FILLED_STAFF, 0)) AS FILLED_STAFF,
  SUM(COALESCE(OPEN_POSITIONS, 0)) AS OPEN_POSITIONS,
  IFF(SUM(COALESCE(REQUIRED_STAFF, 0)) = 0, NULL,
      SUM(COALESCE(FILLED_STAFF, 0)) / SUM(COALESCE(REQUIRED_STAFF, 0))::NUMBER(18, 4)) AS FILL_RATE,
  AVG(TIME_TO_FILL_DAYS) AS AVG_TIME_TO_FILL_DAYS,
  SUM(ACTIVE_PLACEMENT_COUNT) AS ACTIVE_PLACEMENTS,
  SUM(PLANNED_HOURS) AS PLANNED_HOURS,
  SUM(WORKED_HOURS) AS WORKED_HOURS,
  SUM(OVERTIME_HOURS) AS OVERTIME_HOURS
FROM FACT_STAFFING_REQUEST;

CREATE OR REPLACE VIEW VW_PIPELINE_RUNS AS
SELECT
  R.RUN_ID,
  R.BATCH_ID,
  R.SOURCE_SYSTEM,
  R.SOURCE_OBJECT,
  R.TARGET_TABLE,
  R.STATUS,
  R.EXTRACT_STARTED_AT,
  R.EXTRACT_FINISHED_AT,
  R.RAW_LOADED_AT,
  R.CURATED_AT,
  DATEDIFF('second', R.EXTRACT_STARTED_AT, R.EXTRACT_FINISHED_AT) AS RUN_DURATION_SECONDS,
  C.SLA_SECONDS,
  IFF(R.STATUS = 'SUCCEEDED'
      AND R.EXTRACT_FINISHED_AT IS NOT NULL
      AND DATEDIFF('second', R.EXTRACT_STARTED_AT, R.EXTRACT_FINISHED_AT) <= C.SLA_SECONDS,
      TRUE, FALSE) AS WITHIN_RUN_SLA,
  R.ROWS_READ,
  R.ROWS_INSERTED,
  R.ROWS_UPDATED,
  R.ROWS_DELETED,
  R.ROWS_REJECTED,
  R.RETRY_COUNT,
  R.ERROR_CATEGORY,
  R.ERROR_MESSAGE
FROM AMN_DEV.CONTROL.PIPELINE_RUN_LOG R
LEFT JOIN AMN_DEV.CONTROL.INGESTION_CONFIG C
  ON R.SOURCE_SYSTEM = C.SOURCE_SYSTEM
 AND R.SOURCE_OBJECT = C.SOURCE_OBJECT;

CREATE OR REPLACE VIEW VW_PIPELINE_LATEST_STATUS AS
SELECT *
FROM VW_PIPELINE_RUNS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY SOURCE_SYSTEM, SOURCE_OBJECT
  ORDER BY EXTRACT_STARTED_AT DESC
) = 1;

USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE AMN_DEV TO ROLE AMN_BI_ROLE;
GRANT USAGE ON SCHEMA AMN_DEV.MARTS TO ROLE AMN_BI_ROLE;
GRANT USAGE ON WAREHOUSE AMN_BI_WH TO ROLE AMN_BI_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA AMN_DEV.MARTS TO ROLE AMN_BI_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AMN_DEV.MARTS TO ROLE AMN_BI_ROLE;

-- Validation: all queries must succeed using only the BI role and MARTS schema.
USE ROLE AMN_BI_ROLE;
USE WAREHOUSE AMN_BI_WH;
SELECT * FROM AMN_DEV.MARTS.VW_EXECUTIVE_KPIS;
SELECT SOURCE_OBJECT, STATUS, RUN_DURATION_SECONDS, WITHIN_RUN_SLA
FROM AMN_DEV.MARTS.VW_PIPELINE_LATEST_STATUS
ORDER BY SOURCE_OBJECT;
