// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
EVALUATE
    TOPN(100, 'DIM_CANDIDATE')



SELECT
    [Name],
    [Table],
    [DataType]
FROM $SYSTEM.TMSCHEMA_COLUMNS
WHERE [Table] = 'DIM_CANDIDATE'
ORDER BY [Name]
